HellProject/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from HellProject import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_info.urls'), name = 'user_info'),
    path('listview/', include('list.urls'), name='list'),
    path('inquiry/', include('inquiry.urls'), name='inquiry'),
    path('market/', include('market.urls'), name='market'),
]
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inquiry/urls.py
from django.urls.conf import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'inquiry'

urlpatterns=[
    path('CS/', views.CS, name = 'CS'),
    path('FAQ/', views.FAQ, name = 'FAQ'),
]

list/urls.py
from django.urls import path
from django.conf.urls.static import static

from HellProject import settings
from . import views

app_name = 'list'

urlpatterns =[
    path('list_view/', views.list_view, name='list_view'),
    path('helpWrite/', views.helpWrite, name='helpWrite'),
    path('delete/<str:id>', views.delete, name='delete'),
    path('feed_Deatil/<str:id>', views.feed_Detail, name='feed_Detail'),
    path('donate/<str:id1> <str:id2> <str:id3>', views.donate, name='donate'),
]

market/urls.py
from django.urls import path
from django.conf.urls.static import static

from HellProject import settings
from . import views

app_name = 'market'

urlpatterns =[
    path('', views.market_view, name='market_view'),
    path('marketDetail/<str:id>', views.market_Detail, name='market_Detail'),
    path('marketWrite/', views.market_Write, name='market_Write'),
    path('marketDelete/<str:id>', views.market_Delete, name='market_Delete'),
]

user_info/urls.py
from django.urls.conf import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'user_info'

urlpatterns=[
    path('', views.home, name = 'home'),
    path('mypage', views.mypage, name = 'mypage'),
    path('login', views.login_view, name = 'login_view'),
    path('signup', views.signup, name = 'signup'),
    path('logout_view/', views.logout_view, name="logout_view"),

    path('sponserpage/', views.sponserpage, name="sponserpage"),
    path('recentView/<str:email>', views.recentView, name="recentView"),
    path('recentDetail/<str:id>', views.recentDetail, name='recentDetail'),
    path('recentWrite/', views.recentWrite, name="recentWrite"),
]

list/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from datetime import datetime, timedelta
from user_info.models import CustomUser
from django.utils import timezone

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    writer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='users')
    # photo = models.ImageField(verbose_name='사진',upload_to='list/',blank=True, null=True)
    post_time = models.DateTimeField(auto_now_add=True)
    body = models.CharField(max_length=500)
    thumbnail = models.ImageField(verbose_name='썸네일', upload_to='thumbnail/')
    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]
    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.post_time

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days= 1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days= 7):
            time = datetime.now(tz=timezone.utc).date() - self.post_time.date()
            return str(time.days) + '일 전'
        else:
            return False
class Photo(models.Model):
    post = models.ForeignKey(Post,on_delete=CASCADE, null=True, blank=True)
    image = models.ImageField(verbose_name='사진', upload_to='list/',null=True, blank=True)
#    image_thumbnail = ImageSpecField(source='image', processors=[ResizeToFill(120,80)])
#    thumbnail = models.ImageField(verbose_name='썸네일')
    description = models.TextField()
    def __str__(self):
        return self.description

list/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']

list/views.py
from datetime import timedelta
from django.contrib import messages
from django.http.response import HttpResponse
from .models import Post, Photo
from .forms import PostForm
from django.shortcuts import redirect, render
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from user_info.models import CustomUser, UserInfo, whodonate
from django.core.paginator import Paginator
# Create your views here.

def list_view(request):
    post = Post.objects.all().order_by('-id')
    paginator = Paginator(post, 2)
    page = request.GET.get('page')
    post = paginator.get_page(page)
    return render(request, 'html/feed.html', {'posts':post})

@csrf_exempt
def helpWrite(request):
    if not request.user.is_authenticated:
        msg = "Not_auth"
        return render(request, 'html/helpWrite.html', {'msg' : msg})        
    
    userinfo = UserInfo.objects.get(user_email=request.user.email)
    if userinfo.qua != "yes":
        msg = "Not_yes"
        return render(request, 'html/helpWrite.html', {'msg' : msg})

    if request.method == 'POST':
        post = Post()
        post.title = request.POST.get('title')
        post.writer= request.user
        post.post_time = timezone.now()
        post.body = request.POST.get('body')
        post.thumbnail = request.FILES.get('images')
        post.save()
        return redirect('list:list_view')
    else:
        form = PostForm()
        return render(request, 'html/helpWrite.html', {'post':form})

def feed_Detail(request, id):
    post = Post.objects.get(id=id)
    return render(request, 'html/feedDetail.html', {'post':post})

def delete(request, id):
    post = Post.objects.get(id=id)
    post.delete()
    return redirect('list:list_view')

#id1 = 주는사람
#id2 = 받는사람
#id3 = 당시 포스트id
@csrf_exempt
def donate(request, id1, id2, id3):
    if request.method == 'POST':
        donator = CustomUser.objects.get(id=id1)
        receiver = CustomUser.objects.get(id=id2)
        cash = int(request.POST.get('cash'))

        donator_info = UserInfo.objects.get(user_email=donator.email)
        receiver_info = UserInfo.objects.get(user_email=receiver.email)

        if cash > int(donator_info.cash):
            return HttpResponse("돈 더 충전하고 오세요")

        relation = whodonate.objects.create(
            whogetmoney= receiver.email,
            givemoney= str(cash),
            whogivemoney= donator.email,
            what_post = Post.objects.get(id=id3),
            date = timezone.now()
        )
        donator_info.user_totaldonate += cash
        print(receiver_info.cash)
        print("Before : " + str(donator_info.cash))
        print("Before : " + str(receiver_info.cash))
        donator_info.cash = int(donator_info.cash) - cash
        receiver_info.cash = str(int(receiver_info.cash) + cash)
        print("After : " + str(donator_info.cash))
        print("After : " + str(receiver_info.cash))

        donator_info.save()
        receiver_info.save()
    return redirect('list:list_view')

list/templates/html/feed.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'feed.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>후원을 다이렉트로, 후원트</title>
</head>
<body>
<div class="header">
    <ul>
        <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
        <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
        <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
        <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
        <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
        {% if not user.is_authenticated %}
            <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
        {% else %}
            <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
        {% endif %}
    </ul>
</div>

<div class="contentBox">
    <div class="makeDonate">
        <i class="fa fa-plus-circle" aria-hidden="true"></i>
        <div class="verticalTextBox">
            <h2>후원이 필요 하신가요?</h2>
            <h3>사진과 사연을 통해 후원 요청글을 등록해 보세요!</h3>
        </div>
    </div>

    {% for post in posts %}
        <div class="content">
            <div class="title">
                <i class="fa fa-user-circle" aria-hidden="true"></i>
                <div class="titleTextBox">
                    <h2 class="userName">{{ post.writer }}</h2>
                    <h3 class="time">
                        {% if post.created_string == False %}
                            {{ post.created|date:'m월 d일' }}
                        {% else %}
                            {{ post.created_string }}
                        {% endif %}</h3>
                </div>
            </div>
            <h2 class="contents">{{ post.body }}</h2>
            {% if post.thumbnail %}
                <div class="imgBox">
                    <img class="contentImg" src="{{ post.thumbnail.url }}" width='700px' height='700px'>
                </div>
            {% endif %}
            <div class="btnBox">
                <button type="button" onclick="location.href = '{% url 'list:feed_Detail' post.id %}'">더 알아보기 >>
                </button>
            </div>
            <a href="{% url 'list:delete' post.id %}">삭제</a>
        </div>
    {% endfor %}
    <div class="pager">
        <div class="pagerBox">
            <!-- 이전 페이지가 있을때만 보이도록 -->
            {% if posts.has_previous %}
                <a href="?page=1">처음</a>
                <a href="?page={{ posts.previous_page_number }}">이전</a>
            {% endif %}
            <!-- 현재 몇번째 페이지인지 -->
            <span>{{ posts.number }}</span>
            <span>of</span>
            <span>{{ posts.paginator.num_pages }}</span>
            <!-- 다음 페이지가 있을때만 보이도록 -->
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">다음</a>
                <a href="?page={{ posts.paginator.num_pages }}">마지막</a>
            {% endif %}
        </div>
    </div>
</div>
<div class="footer">
    <ul>
        <li><a href="#" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="#" class="navItem">기업소개</a></li>
        <li><a href="#" class="navItem">이용약관</a></li>
        <li><a href="#" class="navItem">개인정보 처리방침</a></li>
        <li><a href="#" class="navItem">고객센터</a></li>
    </ul>
    <span class="line"></span>
    <h2>(주)후원트 (대표이사:후대표) | 대구광역시 수성구 범어천로20 두산위브더제니스 4202호 | 통신판매번호 : 00-00-00-00
        유료직업소개사업등록번호 : (국내) 제000-00000-00000 | (국외) 000-0000-0000 | 사업자등록번호 : 0000-0000-0000
        © WhoWantLab, Inc.</h2>
</div>
</body>
</html>

list/templates/html/feedDetail.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
    <script>
        function newPage() {
            window.location.href = "{% url 'user_info:recentWrite' %}"
        }
    </script>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'feedDetail.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>후원을 다이렉트로, 후원트</title>
</head>

<body>
<div class="popCmmn">
    <div class="popBg" data-num="1"></div>
    <div class="popInnerBox">
        <div class="popHead">
            <h2></h2>
            <h2>후원할 금액 입력</h2>
            <h2 class="close">X</h2></div>
        <form action="{% url 'list:donate' user.id post.writer.id post.id %}" method='POST'>
            {% csrf_token %}
            <div class="popBody">
                <input name='cash' type="number" class="donateAmount"><h2>원</h2>
            </div>
            <div class="popFoot">
                <button class="popCloseBtnCmmn" type="submit" data-num="1">확인</button>
            </div>
        </form>
    </div>
</div>
<div class="header">
    <ul>
        <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
        <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
        <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
        <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
        <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
        {% if not user.is_authenticated %}
            <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
        {% else %}
            <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
        {% endif %}
    </ul>
</div>
<div class="contentBox">
    <div class="makeDonate">
        <!--    <i class="fa fa-plus-circle" aria-hidden="true"></i>-->
        <img src="{% static 'img/logo.png' %}">
        <div class="verticalTextBox">
            <h2>게시글을 확인 후 도움을 주세요!</h2>
            <h3>후원자의 따듯한 마음을 전해드릴게요</h3>
        </div>
    </div>
    <div class="content">

        <div class="title">
            <i class="fa fa-user-circle" aria-hidden="true"></i>
            <div class="titleTextBox">
                <h2 class="userName">{{ post.writer }}</h2>
                <h3 class="time">
                    {% if post.created_string == False %}
                        {{ post.created|date:'m월 d일' }}
                    {% else %}
                        {{ post.created_string }}
                    {% endif %}
                </h3>
            </div>
        </div>
        <h2 class="contents">{{ post.body }}</h2>
        {% if post.thumbnail %}
            <div class="imgBox">
                <img class="contentImg" src="{{ post.thumbnail.url }}">
            </div>
            <div class="btnBox">

                <button type="button" class="donate">후원하기</button>
            </div>
        {% endif %}
    </div>
    <div class="info">
        <h2>거주지역 : 대구광역시</h2>
        <h2>분류 : 결식아동</h2>
        <h2>매너온도 : 37.5</h2>
        <h2>근황 작성도 : 100%</h2>
    </div>
</div>
<div class="footer">
    <ul>
        <li><a href="#" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="#" class="navItem">기업소개</a></li>
        <li><a href="#" class="navItem">이용약관</a></li>
        <li><a href="#" class="navItem">개인정보 처리방침</a></li>
        <li><a href="#" class="navItem">고객센터</a></li>
    </ul>
    <span class="line"></span>
    <h2>(주)후원트 (대표이사:후대표) | 대구광역시 수성구 범어천로20 두산위브더제니스 4202호 | 통신판매번호 : 00-00-00-00
        유료직업소개사업등록번호 : (국내) 제000-00000-00000 | (국외) 000-0000-0000 | 사업자등록번호 : 0000-0000-0000
        © WhoWantLab, Inc.</h2>
</div>
</body>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(function () {
        setPop();
    });

    function setPop() {
        var popOpenBtn = $('.donate');

        popOpenBtn.on('click', function () {
            var clickNum = $(this).attr('data-num');

            $('.popCmmn').fadeIn(200);
        })

        $('.popBg, .popCloseBtnCmmn, .close').on('click', function () {
            $('.popCmmn').fadeOut(200);
        })
    }
</script>
</html>

list/templates/html/helpWrite.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" href="{% static 'helpWrite.css'%}">
  <title>후원 게시글 작성</title>
</head>
<body>
  {% if msg == 'Not_auth' %}
    <script>
      alert("로그인 후 이용가능합니다")
      window.location.href = "{% url 'user_info:login_view' %}"
    </script>
  {% endif %}
  {% if msg == 'Not_yes' %}
    <script>
      alert("해당 기능은 기초수급자만 이용가능합니다!dd")
      window.location.href = "{% url 'user_info:home' %}"
    </script>
  {% endif %}
<div class="header">
  <ul>
    <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
    <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
    <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
    <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
    <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
    <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
    {% if not user.is_authenticated %}
        <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
    {% else %}
        <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
    {% endif %}
  </ul>
</div>
<div class="inputArea">
  <h2>후원 게시글 작성</h2>
  <form action='{% url 'list:helpWrite' %}' method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    
    <textarea placeholder="제목." class="title" name = 'title'></textarea>
    <textarea placeholder="내용을 입력해주세요." class="formText" name = 'body'></textarea>
    
    <input type="file" name = 'images' multiple>
    <input type="submit" value="제출하기" class="csSubmit">

  </form>
</div>
</body>
</html>