HellProject/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from HellProject import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_info.urls'), name = 'user_info'),
    path('listview/', include('list.urls'), name='list'),
    path('inquiry/', include('inquiry.urls'), name='inquiry'),
    path('market/', include('market.urls'), name='market'),
]
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inquiry/urls.py
from django.urls.conf import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'inquiry'

urlpatterns=[
    path('CS/', views.CS, name = 'CS'),
    path('FAQ/', views.FAQ, name = 'FAQ'),
]

list/urls.py
from django.urls import path
from django.conf.urls.static import static

from HellProject import settings
from . import views

app_name = 'list'

urlpatterns =[
    path('list_view/', views.list_view, name='list_view'),
    path('helpWrite/', views.helpWrite, name='helpWrite'),
    path('delete/<str:id>', views.delete, name='delete'),
    path('feed_Deatil/<str:id>', views.feed_Detail, name='feed_Detail'),
    path('donate/<str:id1> <str:id2> <str:id3>', views.donate, name='donate'),
]

market/urls.py
from django.urls import path
from django.conf.urls.static import static

from HellProject import settings
from . import views

app_name = 'market'

urlpatterns =[
    path('', views.market_view, name='market_view'),
    path('marketDetail/<str:id>', views.market_Detail, name='market_Detail'),
    path('marketWrite/', views.market_Write, name='market_Write'),
    path('marketDelete/<str:id>', views.market_Delete, name='market_Delete'),
]

user_info/urls.py
from django.urls.conf import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'user_info'

urlpatterns=[
    path('', views.home, name = 'home'),
    path('mypage', views.mypage, name = 'mypage'),
    path('login', views.login_view, name = 'login_view'),
    path('signup', views.signup, name = 'signup'),
    path('logout_view/', views.logout_view, name="logout_view"),

    path('sponserpage/', views.sponserpage, name="sponserpage"),
    path('recentView/<str:email>', views.recentView, name="recentView"),
    path('recentDetail/<str:id>', views.recentDetail, name='recentDetail'),
    path('recentWrite/', views.recentWrite, name="recentWrite"),
]

user_info/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.db.models.deletion import CASCADE

class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from datetime import datetime, timedelta
from django.utils import timezone

class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class UserInfo(models.Model):
    user_nickname = models.CharField(null=True, max_length=10)
    user_email = models.CharField(null=True, max_length = 30)
    user_phone = models.CharField(null=True, max_length = 30)
    user_image = models.ImageField(upload_to='userinfo/', default="static/profileimage.jpg")
    user_name = models.CharField(null=True, max_length = 20)
    user_account_name = models.CharField(null=True, max_length = 20)
    user_account = models.CharField(null=True, max_length = 30)
    user_totalcash = models.IntegerField(null=True, default=0)
    user_description = models.TextField(default="잘 부탁드립니다!!")
    user_totaldonate = models.IntegerField(default=0, null=True)
    cash = models.IntegerField(null=True, default=0)
    qua = models.CharField(null=True, max_length = 30, blank=True)

    def __str__(self):
        return self.user_email

class whodonate(models.Model):
    whogetmoney = models.CharField(null=True, max_length = 30)
    givemoney = models.CharField(null=True, max_length = 30)
    whogivemoney = models.CharField(null=True, max_length = 30)
    what_post = models.ForeignKey("list.Post", on_delete=CASCADE, related_name="posts")
    date = models.DateTimeField(auto_now_add=True)

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.date

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days= 1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days= 7):
            time = datetime.now(tz=timezone.utc).date() - self.date.date()
            return str(time.days) + '일 전'
        else:
            return False
## abas@naver.com 후원받는사람
## kim@naver.com, tony1234@naver.com 후원하는사람


class Post1(models.Model):
    title = models.CharField(max_length=100)
    writer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='users1')
    photo = models.ImageField(verbose_name='사진',upload_to='userinfo/',blank=True, null=True)
    post_time = models.DateTimeField(auto_now_add=True)
    body = models.CharField(max_length=500)
    
    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

    @property
    def created_string(self):
        if(self.post_time == None):
            self.post_time = timezone.now()
            time = datetime.now(tz=timezone.utc) - self.post_time
        else:
            time = datetime.now(tz=timezone.utc) - self.post_time

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days= 1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days= 7):
            time = datetime.now(tz=timezone.utc).date() - self.post_time.date()
            return str(time.days) + '일 전'
        else:
            return False

user_info/views.py
from django.core import paginator
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.utils import timezone  # pub_date를 위해 import
from django.contrib import auth
from .models import UserInfo, CustomUser, whodonate, Post1
from .form import PostForm
from .GoogleApi import google_api
from list.models import Post

import os

def home(request):
    return render(request, 'index.html')

def login_view(request):
    if request.method == 'POST':
        username = request.POST["userid"]
        password = request.POST["userpw"]
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('user_info:home')
        else:
            return render(request, 'login.html', {'error': "username or passowrd is incorrect"})
    else:
        return render(request, 'login.html')

def signup(request):
    if request.method == "POST":
        if request.POST["user_pw1"] == request.POST["user_pw2"]:
            user = CustomUser.objects.create_user(
                email=request.POST['user_email'], password=request.POST['user_pw1'])
            auth.login(request, user)
            user_contents = UserInfo()
            user_contents.user_email = request.POST['user_email']
            user_contents.user_nickname = request.POST['user_nickname']
            user_contents.user_phone = request.POST['user_num']
            user_contents.user_name = request.POST['user_name']
            user_contents.user_account = request.POST['user_acname']
            user_contents.user_account_name = request.POST['user_acnum']
            user_contents.save()
            return render(request, 'index.html')
        return render(request, 'signup.html')
    return render(request, 'signup.html')



def logout_view(request):
    auth.logout(request)
    return redirect('user_info:home')

def mypage(request):
    if not request.user.is_authenticated:
        msg = "Do Login"
        return render(request, "mypage.html", {'msg':msg})
    user = CustomUser.objects.get(email=request.user.email)
    userinfo = UserInfo.objects.get(user_email=user)
    #돈을 준 사람이 현재 유저인 사람과 같을때, 그니까 현재 유저한테 후원받은사람들 필터링
    my_donate_relation = whodonate.objects.filter(whogivemoney=request.user.email)
    #거기서 중복 제거
    mdr = my_donate_relation.values_list('whogetmoney', flat=True).distinct()
    my_receiver = []
    msg = ""
    for m in mdr:
        my_receiver.append(UserInfo.objects.get(user_email=m))


    if userinfo.qua == "yes":
        return redirect('user_info:sponserpage')
    if request.method == 'POST':
        money = request.POST['mine']
        try:
            money = int(money)
        except:
            msg = "failed"
            return render(request, 'mypage.html', {"error" : msg})

        save_money = int(userinfo.cash)
        userinfo.cash = money + save_money
        userinfo.user_totalcash += money
        userinfo.save()
        msg = "success"
    return render(request, 'mypage.html', {"money" : userinfo.cash,"success":msg ,'receivers':my_receiver ,"temperature" : str(round(0.1 * (userinfo.user_totaldonate / 1000),2))})
# def cash_fill(request):
#     if request.method == 'POST':
#         user = CustomUser.objects.get(email=request.user.email)
#         userinfo = UserInfo.objects.get(user_email=user)
#         money = request.POST['mine']
#         print(money)
#         try:
#             money = int(money)
#         except:
#             return render(request, 'mypage.html', {"error" : "failed"})

#         try:
#             save_money = int(userinfo.cash)
#             userinfo.cash = money + save_money
#             userinfo.user_totalcash += money
#         except:
#             userinfo.cash = money
#         userinfo.save()
#     return render(request, 'mypage.html', {"money" : userinfo.cash, "success": "success", "temperature" : str(0.1 * (userinfo.user_totalcash / 1000))})
    

def recentDetail(request, id):
    post = Post1.objects.get(id=id)
    return render(request, 'recentDetail.html', {'post':post})
def recentWrite(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.writer = request.user
            post.post_time = timezone.now()
            post.photo=request.FILES.get('image')
            path = str(post.photo.path).split('\\')
            post.save()
            t_path  = ''
            if path!=[]:
                for i in path:
                    if i == 'media':
                        t_path = t_path + i + '\\' + 'userinfo' + '\\'
                    elif i.find('jpg') != -1 :
                        t_path = t_path + i
                    else:    
                        t_path = t_path + i + '\\'
                if google_api(t_path):
                    return redirect('user_info:sponserpage')
                else:
                    post.delete()
                    os.remove(t_path)
                return render(request, 'recentWrite.html', {"error" : "error"})
        return redirect('user_info:sponserpage')
    return render(request, 'recentWrite.html')

from django.core.paginator import Paginator
def sponserpage(request):
    user = CustomUser.objects.get(email=request.user.email)
    whos = whodonate.objects.filter(whogetmoney=user)
    posts = Post.objects.filter(writer=request.user)
    paginator = Paginator(posts, 8)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    recent_posts = Post1.objects.filter(writer=request.user).order_by('-post_time')
    recent_paginator = Paginator(recent_posts, 8)
    recent_page = request.GET.get('page')
    recent_posts = recent_paginator.get_page(recent_page)

    return render(request, 'sponserpage.html', {'whos' : whos, 'posts': posts, 'recent_posts':recent_posts})

def recentView(request, email):
    user = CustomUser.objects.get(email=email)
    userinfo = UserInfo.objects.get(user_email = email)
    posts = Post1.objects.filter(writer=user).order_by('post_time')

    return render(request, 'recentView.html', {'posts': posts, 'receiver' : userinfo})

user_info/templates/index.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
    <script>
    function newPage()  {
        {% if not user.is_authenticated %}
            alert("로그인 후 이용할 수 있습니다.") 
            window.location.href = "{% url 'user_info:login_view' %}"            
        {% else %}
            window.location.href = "{% url 'list:list_view' %}"
        {% endif %}
    }
    </script>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <title>후원을 다이렉트로, 후원트</title>
</head>
<script>
    window.setTimeout(function() {
        $(".alert-auto-dismissible").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove();
        });
    }, 4000);
</script>
<body>
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-auto-dismissible alert-dismissible notification-container text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
{% endfor %}
<div class="header1">
    <ul>
        <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
        <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
        <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
        <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
        <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
        {% if not user.is_authenticated %}
            <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
        {% else %}
            <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
        {% endif %}
    </ul>
</div>
<div class="banner">
    <img src="{% static 'img/banner.png' %}" alt="">
    <div class="content">
        <h2>나의 소중한 후원을<br>수수료 없이 다이렉트로, 후원트</h2>
        <h3>지금 후원트와 함께 행복을 나눠보세요.</h3>
        <button type="button" class="startBtn" onclick='newPage()' >지금 시작하기</button>
    </div>
</div>
<div class="intro">
    <div class="contentBox">
        <img src="{% static 'img/donate.svg' %}">
        <div class="textBox">
            <h2>직접 후원이 가능한<br>새로운 플랫폼</h2>
            <h3>내가 원하는 사람에게 직접 후원, 수수료 걱정 없이 바로 후원</h3>
        </div>
    </div>
    <div class="contentBox">
        <div class="textBox">
            <h2>확실한 후원금 관리</h2>
            <h3>나의 기부금이 어디에 쓰였는지 확인 가능</h3>
        </div>
        <img src="{% static 'img/chart.svg' %}">
    </div>
    <div class="contentBox">
        <img src="{% static 'img/share.svg' %}">
        <div class="textBox">
            <h2>후원이 부담스럽다면<br>재능 마켓</h2>
            <h3>내가 가진 재능을 도움이 필요한 사람들에게 나눠보세요</h3>
        </div>
    </div>
    <div class="contentBox">
        <div class="textBox">
            <h2>충전을 이용한 후원<br>시스템</h2>
            <h3>금액을 내마음대로 충전하여 원하는 사람에게 후원을 하세요</h3>
        </div>
        <img src="{% static 'img/money.svg' %}">
    </div>
</div>
<div class="footer">
    <ul>
        <li><a href="#" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="#" class="navItem">기업소개</a></li>
        <li><a href="#" class="navItem">이용약관</a></li>
        <li><a href="#" class="navItem">개인정보 처리방침</a></li>
        <li><a href="#" class="navItem">고객센터</a></li>
    </ul>
    <span class="line"></span>
    <h2>(주)후원트 (대표이사:후대표) | 대구광역시 수성구 범어천로20 두산위브더제니스 4202호 | 통신판매번호 : 00-00-00-00
        유료직업소개사업등록번호 : (국내) 제000-00000-00000 | (국외) 000-0000-0000 | 사업자등록번호 : 0000-0000-0000
        © WhoWantLab, Inc.</h2>
</div>

</body>

user_info/templates/mypage.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'mypage.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.4.1/dist/chart.min.js"></script>
    <title>후원을 다이렉트로, 후원트</title>
</head>
<body>
    {% if msg == "Do Login" %}
    <script>
        alert("로그인 후 이용해주세요");
        window.location.href = "{% url 'user_info:login_view' %}";
    </script>
    {% endif %}
    {% if error == "failed" %}
    <script>
        alert("올바른 금액을 작성해주세요.");
    </script>
    {% endif %}
    {% if success == "success" %}
    <script>
        alert("충전에 성공하였습니다.");
    </script>
    {% endif %}
<div class="header">
    <ul>
        <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
        <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
        <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
        <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
        <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
        {% if not user.is_authenticated %}
            <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
        {% else %}
            <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
        {% endif %}
    </ul>
</div>
<div class="contentBox">
    <div class="userProfile">
        <i class="fa fa-user-circle-o" aria-hidden="true"></i>
        <h3>{{request.user.email}}</h3>
    </div>
    <div class="horizontalBox">
        <div class="pointBox">
            <div class="titleBox">
                <i class="fa fa-credit-card-alt" aria-hidden="true"></i>
                <div class="titleText">
                    <h2>당신의 보유 포인트</h2>
                    {% if money is 0 %}
                        <h3>금액이 하나도 없어요!</h3>
                    {% else %}
                        <h3>{{money}}</h3>
                    {% endif %}
                </div>
            </div>
        <form action = "{% url 'user_info:mypage' %}" method="POST" >
            {% csrf_token %}
            <div class="inputArea">
                <input type="number" placeholder="금액 입력" name = "mine" class="pointInput">
                <button input="submit">충전하기</button>
            </div>
        </form>
        </div>
        <div class="tempBox">
            <div class="titleBox">
                <i class="fa fa-thermometer-empty" aria-hidden="true"></i>
                <div class="titleText">
                    <h2>당신의 마음의 온도는 </h2>
                    <h3>{{temperature}}℃</h3>
                </div>
            </div>
            <div class="inputArea">
                <button type="button">후원하러 가기</button>
            </div>
        </div>
    </div>
    <h2>내가 후원했던 사람 어떻게 살고있을까??</h2>

    <div class="donateList">
        <div class="swiper-container mySwiper">
            <div class="swiper-wrapper">
            {% for receiver in receivers %}
                <div class="swiper-slide">
                    <h2>{{receiver.user_nickname}}</h2>
                    <img src="{{receiver.user_image.url}}">
                    <h3>{{receiver.user_description}}</h3>
                    <button type="button" onclick="location.href = '{% url 'user_info:recentView' receiver.user_email %}'">근황보기</button>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>

</div>

<div class="footer">
    <ul>
        <li><a href="#" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="#" class="navItem">기업소개</a></li>
        <li><a href="#" class="navItem">이용약관</a></li>
        <li><a href="#" class="navItem">개인정보 처리방침</a></li>
        <li><a href="#" class="navItem">고객센터</a></li>
    </ul>
    <span class="line"></span>
    <h2>(주)후원트 (대표이사:후대표) | 대구광역시 수성구 범어천로20 두산위브더제니스 4202호 | 통신판매번호 : 00-00-00-00
        유료직업소개사업등록번호 : (국내) 제000-00000-00000 | (국외) 000-0000-0000 | 사업자등록번호 : 0000-0000-0000
        © WhoWantLab, Inc.</h2>
</div>

<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script>
    var swiper = new Swiper(".mySwiper", {
        slidesPerView: 3,
        spaceBetween: 30,
        freeMode: true,

    });
</script>
</body>

user_info/templates/sponserpage.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'sponserpage.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.4.1/dist/chart.min.js"></script>
    <title>후원을 다이렉트로, 후원트</title>
</head>
<body>
    <div class="header">
        <ul>
            <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
            <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
            <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
            <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
            <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
            <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
            {% if not user.is_authenticated %}
                <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
            {% else %}
                <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
            {% endif %}
        </ul>
    </div>

    <div class="profile_box" align=middle>
        <i class="fa fa-user-circle-o" aria-hidden="true"></i>
        <p class="email">{{request.user.email}}</p>

        <div class="inner_box1">
         
            <table class="table_1" >
                <tr>
                    <th colspan="2">
                        <i class="fa fa-credit-card-alt credit" aria-hidden="true"></i>
                        <p>&nbsp;&nbsp;후원 내역</p>
                    </th>
                </tr>
                <tr>
                    <td scope="col" class="first_text">
                    </td>
                </tr>
            </table>
    
            <div id="contents">
                <div class="bx_tb1">
                        <table>
                        {% for who in whos %}
                        <tr>
                            <td id="spon-date">
                            {% if who.created_string == False %}
                            {{who.created|date:'m월 d일'}}
                            {% else %}
                            {{who.created_string}}
                            {% endif %}</h3>
                            </td>
                            <td id="spon-nickname">
                                {{ who.whogivemoney }}
                            </td>
                            <td id="spon-money">
                                {{ who.givemoney }}원
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
           
                </div>
            </div>
        </div>


        <div class="inner_box3">
            <p class="donate-title">작성게시글</p>
            <div class="main">
                <input id="tab1" type="radio" name="tabs" checked>
                <label for="tab1">도와주세요</label>
        
                <input id="tab2" type="radio" name="tabs">
                <label for="tab2">보여주세요</label>
                <section id="content1">
                {% for post in posts %}
                    <div class="image-card">
                        <img src="{{post.thumbnail.url}}">
                        <p class="title">{{post.title}}</p>
                        <p class="content">{{post.body}}</p>
                        <button type="button" onclick="location.href = '{% url 'list:feed_Detail' post.id%}'">자세히보기</button>
                    </div>
                {% endfor %}
                    <button type="button" class="write-btn" onclick="location.href = '{% url 'list:helpWrite'%}'">글작성하기</button>
                    <!-- 이전 페이지가 있을때만 보이도록 -->
    {% if posts.has_previous %} 
    <a href="?page=1">처음</a>
    <a href="?page={{posts.previous_page_number}}">이전</a>
    {% endif %}
<!-- 현재 몇번째 페이지인지 -->
    <span>{{posts.number}}</span>
    <span>of</span>
    <span>{{posts.paginator.num_pages}}</span>
<!-- 다음 페이지가 있을때만 보이도록 -->
    {% if posts.has_next %}
    <a href="?page={{posts.next_page_number}}">다음</a>
    <a href="?page={{posts.paginator.num_pages}}">마지막</a>
    {% endif %}
                </section>

                <section id="content2">
                {% for post in recent_posts %}
                    <div class="image-card">
                    {% if post.photo %}
                        <img src="{{post.photo.url}}">
                    {% endif %}
                        <p class="title">{{post.title}}</p>
                        <p class="content">{{post.body}}</p>
                        <button type="button" onclick="location.href = '{% url 'user_info:recentDetail' post.id %}'">자세히보기</button>
                    </div>
                {% endfor %}
                    <button type="button" class="write-btn" onclick="location.href = '{% url 'user_info:recentWrite'%}'">글작성하기</button>
                    <!-- 이전 페이지가 있을때만 보이도록 -->
                    <br>
    {% if recent_posts.has_previous %} 
    <a href="?page=1">처음</a>
    <a href="?page={{recent_posts.previous_page_number}}">이전</a>
    {% endif %}
<!-- 현재 몇번째 페이지인지 -->
    <span>{{recent_posts.number}}</span>
    <span>of</span>
    <span>{{recent_posts.paginator.num_pages}}</span>
<!-- 다음 페이지가 있을때만 보이도록 -->
    {% if recent_posts.has_next %}
    <a href="?page={{recent_posts.next_page_number}}">다음</a>
    <a href="?page={{recent_posts.paginator.num_pages}}">마지막</a>
    {% endif %}
                </section>
            </div>
        </div>
    </div>
</body>