HellProject/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from HellProject import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_info.urls'), name = 'user_info'),
    path('listview/', include('list.urls'), name='list'),
    path('inquiry/', include('inquiry.urls'), name='inquiry'),
    path('market/', include('market.urls'), name='market'),
]
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inquiry/urls.py
from django.urls.conf import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'inquiry'

urlpatterns=[
    path('CS/', views.CS, name = 'CS'),
    path('FAQ/', views.FAQ, name = 'FAQ'),
]

list/urls.py
from django.urls import path
from django.conf.urls.static import static

from HellProject import settings
from . import views

app_name = 'list'

urlpatterns =[
    path('list_view/', views.list_view, name='list_view'),
    path('helpWrite/', views.helpWrite, name='helpWrite'),
    path('delete/<str:id>', views.delete, name='delete'),
    path('feed_Deatil/<str:id>', views.feed_Detail, name='feed_Detail'),
    path('donate/<str:id1> <str:id2> <str:id3>', views.donate, name='donate'),
]

market/urls.py
from django.urls import path
from django.conf.urls.static import static

from HellProject import settings
from . import views

app_name = 'market'

urlpatterns =[
    path('', views.market_view, name='market_view'),
    path('marketDetail/<str:id>', views.market_Detail, name='market_Detail'),
    path('marketWrite/', views.market_Write, name='market_Write'),
    path('marketDelete/<str:id>', views.market_Delete, name='market_Delete'),
]

user_info/urls.py
from django.urls.conf import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'user_info'

urlpatterns=[
    path('', views.home, name = 'home'),
    path('mypage', views.mypage, name = 'mypage'),
    path('login', views.login_view, name = 'login_view'),
    path('signup', views.signup, name = 'signup'),
    path('logout_view/', views.logout_view, name="logout_view"),

    path('sponserpage/', views.sponserpage, name="sponserpage"),
    path('recentView/<str:email>', views.recentView, name="recentView"),
    path('recentDetail/<str:id>', views.recentDetail, name='recentDetail'),
    path('recentWrite/', views.recentWrite, name="recentWrite"),
]

market/models.py
from django.db import models
from user_info.models import CustomUser
from datetime import datetime, timedelta
from django.utils import timezone
# Create your models here.

class MarketPost(models.Model):
    title = models.CharField(max_length=100)
    writer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='user')
    post_time = models.DateTimeField(auto_now_add=True, verbose_name="등록 시간")
    body = models.CharField(max_length=500)
    thumbnail = models.ImageField(verbose_name='썸네일', upload_to='market/', null=True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.post_time

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days= 1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days= 7):
            time = datetime.now(tz=timezone.utc).date() - self.post_time.date()
            return str(time.days) + '일 전'
        else:
            return False

market/views.py
from django.core import paginator
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from .models import MarketPost
from django.utils import timezone
from django.core.paginator import Paginator

# Create your views here.

def market_view(request):
    post = MarketPost.objects.all().order_by('-id')
    paginator = Paginator(post, 3)
    page = request.GET.get('page')
    post = paginator.get_page(page)

    return render(request, 'market.html', {'posts':post})

def market_Detail(request,id):
    post = MarketPost.objects.get(id=id)
    return render(request, 'marketDetail.html', {'post':post})

@csrf_exempt
def market_Write(request):
    if request.method == 'POST':
        post = MarketPost()
        post.title = request.POST.get('title')
        post.writer= request.user
        post.post_time = timezone.now()
        post.body = request.POST.get('body')
        post.thumbnail = request.FILES.get('image')
        post.save()
        return redirect('market:market_view')
    return render(request, 'marketWrite.html')

def market_Delete(request, id):
    post = MarketPost.objects.get(id=id)
    post.delete()
    return redirect('market:market_view')

market/templates/market.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'market.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>후원을 다이렉트로, 후원트</title>
</head>
<body>
<div class="header">
    <ul>
        <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
        <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
        <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
        <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
        <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
        {% if not user.is_authenticated %}
            <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
        {% else %}
            <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
        {% endif %}
    </ul>
</div>

<div class="contentBox">
    <div class="makeDonate">
        <i class="fa fa-plus-circle" aria-hidden="true"></i>
        <div class="verticalTextBox">
            <h2>도움을 주고싶나요?</h2>
            <h3>내가 가진 재능을 다른사람에게 공유해 주세요!</h3>
        </div>
    </div>
    {% for post in posts %}
        <div class="content">
            <div class="title">
                <i class="fa fa-user-circle" aria-hidden="true"></i>
                <div class="titleTextBox">
                    <h2 class="userName">{{ post.writer }}</h2>
                    <h3 class="time">
                        {% if post.created_string == False %}
                            {{ post.created|date:'m월 d일' }}
                        {% else %}
                            {{ post.created_string }}
                        {% endif %}
                    </h3>
                </div>
            </div>
            <h2 class="contents">{{ post.body }}</h2>
            {% if post.thumbnail %}
                <div class="imgBox">
                    <img class="contentImg" src="{{ post.thumbnail.url }}">
                </div>
            {% endif %}
            <div class="btnBox">
                <button type="button" onclick="location.href='{% url 'market:market_Detail' post.id %}'">더 알아보기 >>
                </button>
            </div>
        </div>
    {% endfor %}
    <div class="pager">
        <div class="pagerBox">
            <!-- 이전 페이지가 있을때만 보이도록 -->
            {% if posts.has_previous %}
                <a href="?page=1">처음</a>
                <a href="?page={{ posts.previous_page_number }}">이전</a>
            {% endif %}
            <!-- 현재 몇번째 페이지인지 -->
            <span>{{ posts.number }}</span>
            <span>of</span>
            <span>{{ posts.paginator.num_pages }}</span>
            <!-- 다음 페이지가 있을때만 보이도록 -->
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">다음</a>
                <a href="?page={{ posts.paginator.num_pages }}">마지막</a>
            {% endif %}
        </div>
    </div>
</div>
<div class="footer">
    <ul>
        <li><a href="#" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="#" class="navItem">기업소개</a></li>
        <li><a href="#" class="navItem">이용약관</a></li>
        <li><a href="#" class="navItem">개인정보 처리방침</a></li>
        <li><a href="#" class="navItem">고객센터</a></li>
    </ul>
    <span class="line"></span>
    <h2>(주)후원트 (대표이사:후대표) | 대구광역시 수성구 범어천로20 두산위브더제니스 4202호 | 통신판매번호 : 00-00-00-00
        유료직업소개사업등록번호 : (국내) 제000-00000-00000 | (국외) 000-0000-0000 | 사업자등록번호 : 0000-0000-0000
        © WhoWantLab, Inc.</h2>
</div>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(".makeDonate").click(function () {
        $(location).attr("href", "http://127.0.0.1:8000/market/marketWrite/");
    });
</script>
</body>
</html>

market/templates/marketDetail.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'marketDetail.css'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>후원을 다이렉트로, 후원트</title>
</head>
<body>
<div class="header">
    <ul>
        <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
        <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
        <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
        <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
        <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
        {% if not user.is_authenticated %}
            <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
        {% else %}
            <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
        {% endif %}
    </ul>
</div>

<div class="contentBox">
    <div class="makeDonate">
        <!--    <i class="fa fa-plus-circle" aria-hidden="true"></i>-->
        <img src="../img/logo.png">
        <div class="verticalTextBox">
            <h2>해당 재능이 필요하신가요?</h2>
            <h3>재능마켓에서 재능을 요청해 보세요!</h3>
        </div>
    </div>
    <div class="content">
        <div class="title">
            <i class="fa fa-user-circle" aria-hidden="true"></i>
            <div class="titleTextBox">
                <h2 class="userName">{{post.writer}}</h2>
                <h3 class="time">
                 {% if post.created_string == False %}
                {{post.created|date:'m월 d일'}}
                {% else %}
                {{post.created_string}}
                {% endif %}
                </h3>
            </div>
        </div>
        <h2 class="contents">{{post.body}}</h2>
        <div class="imgBox">
            <img class="contentImg" src="{{post.thumbnail.url}}">
        </div>
        <div class="btnBox">
            <button type="button">신청하기</button>
        </div>
    </div>
</div>
<div class="footer">
    <ul>
        <li><a href="#" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="#" class="navItem">기업소개</a></li>
        <li><a href="#" class="navItem">이용약관</a></li>
        <li><a href="#" class="navItem">개인정보 처리방침</a></li>
        <li><a href="#" class="navItem">고객센터</a></li>
    </ul>
    <span class="line"></span>
    <h2>(주)후원트 (대표이사:후대표) | 대구광역시 수성구 범어천로20 두산위브더제니스 4202호 | 통신판매번호 : 00-00-00-00
        유료직업소개사업등록번호 : (국내) 제000-00000-00000 | (국외) 000-0000-0000 | 사업자등록번호 : 0000-0000-0000
        © WhoWantLab, Inc.</h2>
</div>
</body>
</html>

market/templates/marketWrite.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'marketWrite.css'%}">
    <title>재능 마켓 작성</title>
</head>
<body>
<div class="header">
    <ul>
        <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
        <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
        <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
        <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
        <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
        {% if not user.is_authenticated %}
            <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
        {% else %}
            <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
        {% endif %}
    </ul>
</div>
<div class="inputArea">
    <h2>재능 마켓 게시글 작성</h2>
    <form action='{% url 'market:market_Write'%}' method='POST' enctype='multipart/form-data'>
        {% csrf_token %}
        <textarea name="title" placeholder="제목." class="title"></textarea>
        <textarea name="body" placeholder="내용을 입력해주세요." class="formText"></textarea>
        <input name='image' type="file" multiple>
        <input type="submit" value="제출하기" class="csSubmit">
    </form>
</div>
</body>
</html>